{{- range $key, $value := .Values.persistentVolume }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $value.name }}-pv
spec:
    capacity:
        storage: {{ $value.storage }}
    volumeMode: Filesystem
    accessModes:
        - {{ $value.accessModes }}
    storageClassName: {{ $value.storageClassName | default "efs-sc" }}
    persistentVolumeReclaimPolicy: {{ $value.reclaimPolicy }}
    csi:
        driver: {{ $value.driver }}
        volumeHandle: "{{ $value.volumeHandle }}:{{ $value.subPath }}"
{{- end }}
