{{- range $key, $value := .Values.persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $value.name }}-pvc
  namespace: {{ $.Values.namespace }}
spec:
    accessModes:
        - {{ $value.accessModes }}
    storageClassName: {{ $value.storageClassName | default "efs-sc" }}
    resources:
        requests:
          storage: {{ $value.storage }}
{{- end }}
