{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "basic-service.name" .}}
  namespace: {{.Values.namespace}}
  annotations:
    harness.io/skip-versioning: "true"
  labels:
    app: {{template "basic-service.name" .}}
    {{- if .Values.labels }}
    {{- include "basic-service.labels" $ | indent 4}}
    {{- end }}
data:
{{ tpl (toYaml .Values.env.config) . | indent 2}}
---
{{- end}}

{{- if .Values.env.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{template "basic-service.name" .}}
  namespace: {{.Values.namespace}}
  annotations:
    harness.io/skip-versioning: "true"
  labels:
    app: {{template "basic-service.name" .}}
    {{- if .Values.labels }}
    {{- include "basic-service.labels" $ | indent 4}}
    {{- end }}
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---
{{- end}}

{{- if and .Values.dockercfg (not .Values.dockercfgOverride)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{template "basic-service.name" .}}-dockercfg
  namespace: {{.Values.namespace}}
  annotations:
    harness.io/skip-versioning: "true"
  labels:
    app: {{template "basic-service.name" .}}
    {{- if .Values.labels }}
    {{- include "basic-service.labels" $ | indent 4}}
    {{- end }}
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
{{- end}}
