{{- range $key, $value := .Values.storageClass }}
{{ if $value.create }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $value.name }}
provisioner: {{ $value.provisioner }}
{{ end }}
{{- end }}
