---
- name: Manage storage/data setup
  ansible.builtin.include_tasks: "common/storage-setup.yml"

- name: Setup service infrastructure topology
  ansible.builtin.include_tasks: "{{ setupMode }}/setup.yml"
