---
- name: Create a secured node to provision to
  when: create_secure_node|bool
  ansible.builtin.include_tasks: common/secure-node-setup.yml

- name: Manage storage/data setup
  ansible.builtin.include_tasks: common/storage-setup.yml

- name: Setup service infrastructure topology
  ansible.builtin.include_tasks: "{{ setup_mode }}/setup.yml"

- name: Manage networking and IP tables setup
  when: setup_iptables|bool
  ansible.builtin.include_tasks: common/network-setup.yml
