---
- name: Uninstall provisioned container components
  when: uninstall|bool == true
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify: Container uninstall
  always:
    - name: End play following uninstallation
      meta: end_play

# Compile container resource lists

- name: Determine service container volume list
  set_fact:
    volumeList: "{{ volumeList + [workDir + item.value.destinationPath + ':' + item.value.destinationPath] }}"
  with_dict: "{{ config }}"

- name: Add data DIRs to container volume list
  set_fact:
    volumeList: "{{ volumeList + [item.value.hostPath + ':' + item.value.appPath] }}"
  with_dict: "{{ dataDirs }}"

- name: Determine service container port list
  set_fact:
    portList: "{{ portList + [item.value.ingressPort|string + ':' + item.value.servicePort|string] }}"
  with_dict: "{{ ports }}"

# ---

- name: Start service container
  community.docker.docker_container:
    name: "{{ name }}"
    image: "{{ image }}"
    user: "{{ user | default(omit) }}:{{ group | default(omit) }}"
    command: "{{ command | default(omit) }}"
    env: "{{ configEnv }}"
    published_ports: "{{ portList }}"
    volumes: "{{ volumeList }}"
    cpus: "{{ resources.cpuLimit }}"
    memory: "{{ resources.memLimit }}"
    restart_policy: "{{ restartPolicy }}"
