---
- name: Start service container
  community.docker.docker_container:
    name: "{{ name }}"
    image: "{{ image }}"
    user: "{{ user | default('root') }}"
    command: "{{ command | default(omit) }}"
    env: "{{ config_env }}"
    published_ports: "{{ _port_list }}"
    network_mode: "{{ network_mode }}"
    volumes: "{{ _volume_list }}"
    cpus: "{{ cpus }}"
    memory: "{{ memory }}"
    restart_policy: "{{ restart_policy }}"

# Reset volume_list for subsequent iterations
- name: Reset volume_list
  ansible.builtin.set_fact:
    volume_list: []

# Reset port_list for subsequent iterations
- name: Reset port_list
  ansible.builtin.set_fact:
    port_list: []
