---
# Compile container resource lists

- name: Determine service container volume list
  ansible.builtin.set_fact:
    volume_list: "{{ volume_list + [item.value.destinationPath | dirname + ':' + item.value.destinationPath | dirname] }}"
  with_dict: "{{ config }}"

- name: Add data DIRs to container volume list
  ansible.builtin.set_fact:
    volume_list: "{{ volume_list + [item.value.hostPath + ':' + item.value.appPath] }}"
  with_dict: "{{ data_dirs }}"

- name: Determine service container port list
  ansible.builtin.set_fact:
    port_list: "{{ port_list + [item.value.ingressPort | string + ':' + item.value.servicePort | string] }}"
  with_dict: "{{ ports }}"

# ---

- name: Start service container
  community.docker.docker_container:
    name: "{{ name }}"
    image: "{{ image }}"
    command: "{{ command | default(omit) }}"
    env: "{{ config_env }}"
    published_ports: "{{ port_list }}"
    network_mode: "{{ network_mode }}"
    volumes: "{{ volume_list }}"
    cpus: "{{ cpus }}"
    memory: "{{ memory }}"
    restart_policy: "{{ restart_policy }}"

# Reset volume_list for subsequent iterations
- name: Reset volume_list
  ansible.builtin.set_fact:
    volume_list: []

# Reset port_list for subsequent iterations
- name: Reset port_list
  ansible.builtin.set_fact:
    port_list: []
