---
- name: Ensure existence of host data dir
  when: hostDataDir is defined
  become: true
  ansible.builtin.file:
    path: "{{ hostDataDir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Ensure existence of operations/work dir
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}{{ item.value.destinationPath | dirname }}"
    state: directory
    mode: "0755"
  with_dict: "{{ config }}"

- name: Generate local rendering of service config files
  ansible.builtin.copy:
    content: "{{ item.value.data | default(omit) }}"
    dest: "{{ work_dir }}/{{ item.value.destinationPath }}"
    mode: "{{ item.value.mode | default(644) }}"
    src: "{{ item.value.sourcePath | default(omit) }}"
  with_dict: "{{ config }}"
