---
- name: Ensure existence of host data dir
  when: host_data_dir is defined
  become: true
  ansible.builtin.file:
    path: "{{ host_data_dir }}"
    state: directory
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ group | default(user) | default(ansible_user) }}"
    mode: "0755"

- name: Ensure existence of config dir
  become: true
  ansible.builtin.file:
    path: "{{ host_data_dir + item.value.destinationPath | dirname }}"
    state: directory
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ group | default(user) | default(ansible_user) }}"
    mode: "0755"
  with_dict: "{{ config }}"

- name: Generate local rendering of service config files
  ansible.builtin.copy:
    content: "{{ item.value.data | default(omit) }}"
    dest: "{{ host_data_dir + item.value.destinationPath }}"
    mode: "{{ item.value.mode | default(644) }}"
    src: "{{ item.value.sourcePath | default(omit) }}"
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ group | default(user) | default(ansible_user) }}"
  with_dict: "{{ config }}"

- name: Ensure existence of host data dirs
  become: true
  ansible.builtin.file:
    path: "{{ item.value.hostPath }}"
    state: directory
    mode: "0755"
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ group | default(user) | default(ansible_user) }}"
  with_dict: "{{ data_dirs }}"
