---
- name: Ensure existence of host data dir
  when: hostDataDir is defined
  become: true
  file:
    path: "{{ hostDataDir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777
