---
- name: Ensure Helm is installed
  ansible.builtin.command: helm version
  register: helm_version
  ignore_errors: true

- name: Install Helm on Linux distributions
  ansible.builtin.package:
    name: helm
    state: present
  when:
    - ansible_os_family not in ['Darwin']
    - helm_version.failed

- name: Install Helm on macOS
  community.general.homebrew:
    name: helm
    state: present
  when:
    - ansible_os_family == 'Darwin'
    - helm_version.failed

- name: Install Helm via script on other systems
  ansible.builtin.command: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when:
    - ansible_os_family not in ['Debian', 'RedHat', 'Darwin']
    - helm_version.failed
  args:
    creates: /usr/local/bin/helm

- name: Deploy Helm chart
  kubernetes.core.helm:
    name: "{{ name }}"
    chart_ref: "{{ helm_chart_path }}"
    release_namespace: "{{ helm_namespace }}"
    values_files:
      - "{{ helm_values_path }}"
