name: Basic-Service Continuous-Integration
run-name: CI ${{ github.repository }} - ${{ github.ref }} job 🚀
on:
  push:
    branches: [main]
  pull_request:
jobs:
  Build-Test-Service-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Lint yaml and Ansible configs
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint==6.12.1 yamllint==1.29.0
          yamllint --config-file ./tests/yaml-lint.yml .
          ansible-lint --config-file ./tests/ansible-lint.yml .
